-- 05_options_unit01.sql
BEGIN;
INSERT INTO challenge_options (id, challenge_id, text, correct, image_src, audio_src) VALUES
(1, 3, 'Giving a computer a set of instructions to follow.', true, NULL, NULL),
(2, 3, 'Making a computer think for itself.', false, NULL, NULL),
(3, 3, 'Fixing broken hardware.', false, NULL, NULL),
(4, 4, 'powerful yet easy to read and write.', true, NULL, NULL),
(5, 4, 'very difficult to learn.', false, NULL, NULL),
(6, 5, 'It will follow the wrong instructions exactly.', true, NULL, NULL),
(7, 5, 'It will fix the instructions for you automatically.', false, NULL, NULL),
(8, 8, 'They only do exactly what you tell them to do.', true, NULL, NULL),
(9, 8, 'They can guess what you want even if you type it wrong.', false, NULL, NULL),
(10, 12, 'print()', true, NULL, NULL),
(11, 12, 'show()', false, NULL, NULL),
(12, 12, 'display()', false, NULL, NULL),
(13, 13, 'Quotes " "', true, NULL, NULL),
(14, 13, 'Brackets [ ]', false, NULL, NULL),
(15, 14, 'Codez', true, NULL, NULL),
(16, 14, '"Codez"', false, NULL, NULL),
(17, 14, 'Error', false, NULL, NULL),
(18, 17, 'Because Python needs quotes to know it is text.', true, NULL, NULL),
(19, 17, 'Because Hello is spelled wrong.', false, NULL, NULL),
(20, 21, 'A way to store information in a program.', true, NULL, NULL),
(21, 21, 'A type of error.', false, NULL, NULL),
(22, 21, 'A way to display text on the screen.', false, NULL, NULL),
(23, 22, 'The equals sign (=)', true, NULL, NULL),
(24, 22, 'The plus sign (+)', false, NULL, NULL),
(25, 23, 'Alex', true, NULL, NULL),
(26, 23, 'name', false, NULL, NULL),
(27, 23, '"Alex"', false, NULL, NULL),
(28, 26, 'Because quotes tell Python to print the literal word, not what''s inside the box.', true, NULL, NULL),
(29, 26, 'Because variables only hold numbers.', false, NULL, NULL),
(30, 30, 'To leave notes in the code for humans to read.', true, NULL, NULL),
(31, 30, 'To make the computer run faster.', false, NULL, NULL),
(32, 30, 'To store data like a variable.', false, NULL, NULL),
(33, 31, '#', true, NULL, NULL),
(34, 31, '/', false, NULL, NULL),
(35, 31, '!', false, NULL, NULL),
(36, 32, 'Banana', true, NULL, NULL),
(37, 32, 'Apple
Banana', false, NULL, NULL),
(38, 32, 'Apple', false, NULL, NULL),
(39, 35, 'Yes, you can ''comment out'' the broken line so Python ignores it while you fix other things.', true, NULL, NULL),
(40, 35, 'No, comments have no effect on code execution.', false, NULL, NULL),
(41, 39, 'A typo in the spelling or grammar of the code.', true, NULL, NULL),
(42, 39, 'A virus in the computer.', false, NULL, NULL),
(43, 39, 'When the internet disconnects.', false, NULL, NULL),
(44, 40, 'No, they are normal. They just mean the computer needs you to fix a typo.', true, NULL, NULL),
(45, 40, 'Yes, you should never get an error.', false, NULL, NULL),
(46, 41, 'It is missing the starting quote.', true, NULL, NULL),
(47, 41, 'It is missing a closing parenthesis.', false, NULL, NULL),
(48, 44, 'Because computers cannot guess your intentions; they need exact instructions.', true, NULL, NULL),
(49, 44, 'Because Python is an old language.', false, NULL, NULL),
(50, 47, 'Using print()', true, NULL, NULL),
(51, 47, 'Using a variable', false, NULL, NULL),
(52, 48, 'The # symbol', true, NULL, NULL),
(53, 48, 'The = symbol', false, NULL, NULL),
(54, 49, 'A variable', true, NULL, NULL),
(55, 49, 'A comment', false, NULL, NULL)
ON CONFLICT (id) DO NOTHING;
SELECT setval('challenge_options_id_seq', (SELECT MAX(id) FROM challenge_options));
COMMIT;